baseURL = 'https://akufarish.my.id/'
languageCode = 'en-us'
title = 'Today I Learn - Farish'
theme = ["PaperMod"]

[params.homeInfoParams]
    Title = "Hallo hallo"
    Content = "Ini website untuk mendokumentasi apa yang ku pelajari aja sih. Makasih kalau ada yang baca."

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/akufarish"

[[params.socialIcons]]
    name = "instagram"
    url = "https://www.instagram.com/akuparish"

[[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/farish-asqalani"

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"
  lang = "language"

[[menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 10